name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - run: cargo test

  clippy-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - run: cargo clippy --all --tests
